### ISSUE TITLE
states in use not disting country

### ISSUE THREAD

**Issue by naja7host** [tysonphillips/states_countries#1]
hello tyson, 

in states list in use , is not distingue wich country belong . 

for exemple a user from usa that has states "AL" , in the plugin it will list all the states that has code "AL" as in use, so is not possible to delete it if we want to delete . and it mark the stats and country in use .

**Comment by tysonphillips** [comment]
Not sure I follow. Could you clarify?

The plugin lists each state once you click on a country. So clicking on the United States table row will list each state in another table below it. It's not necessary to show the country in this table since you had just clicked on the country table row to view it. Is this what you're referring to?

**Comment by naja7host** [comment]
to test .list all countries . select jordan as country. it will list that some stats are in use . so impossible to delete them .

this is because the stats hs the same code as the US stats .

**Comment by tysonphillips** [comment]
Thanks for finding that issue. I've released version 1.0.1 to address it.
